config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/admin', :to => 'sessions#admin_new'
  end

  resources :albums do
    member do
      get :add_photos_form
      put :add_photos
    end
  end
  resources :photos
  resources :welcome, only: [:index]

  root to: "welcome#index"
end

app/models/album.rb
class Album < ApplicationRecord
  extend FriendlyId

  has_many :photos, dependent: :destroy
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :places

  validates_presence_of :external_id
  friendly_id :external_id

  def self.find_or_create(data)
    album = self.find_or_create_by(external_id: data["id"]) do |album|
      album.title = data["title"]
    end
    album.update(cover_photo_url: data["coverPhotoBaseUrl"])
    album
  end

  def authors
    [author, photos.pluck(:author)].flatten.uniq.compact.join(", ")
  end

  def place_names
    places.pluck(:name).uniq.compact.join(", ")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :album

  validates_presence_of :external_id

  def self.find_or_create(data, album, author)
    Rails.cache.write("#{data["id"]}_url", "#{data["baseUrl"]}=w500-h500", expires_in: 1.hour)
    self.find_or_create_by(external_id: data["id"]) do |photo|
      photo.date = data["mediaMetadata"]["creationTime"]
      photo.album_id = album.id
      photo.author = author || album.author
    end
  end

  def url
    Rails.cache.fetch("#{external_id}_url", expires_in: 1.hour) do
      PhotoService.new.photo(external_id)["baseUrl"] + "=w500-h500"
    end
  end
end

app/models/place.rb
class Place < ApplicationRecord
  validates_presence_of :name
  has_and_belongs_to_many :albums
  has_and_belongs_to_many :photos
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates_presence_of :name
  has_and_belongs_to_many :albums
  has_and_belongs_to_many :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :find_album, only: [:show, :edit, :update, :add_photos, :add_photos_form]
  before_action :authenticate_admin_user!, only: [:index]

  def index
    @q = Album.where(id: photo_service.album_ids).ransack(params[:q])
    @albums = @q.result(distinct: true).reverse_order
  end

  def show
    @photos = photo_service.album_photos(@album)
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params.slice("title", "year", "author", "agreed_to_publish"))
    @album.external_id = photo_service.create_album_id(@album.title)
    if images.count > 50
      flash[:error] = 'Możesz dodać maksymalnie 50 zdjęć, wybierz najlepsze'
      render :new
    elsif images.count < 1
      flash[:error] = 'Dodaj chociaż jedno zdjęcie'
      render :new
    elsif @album.save
      update_tags
      update_places
      add_images

      redirect_to @album
    else
      flash[:error] = "Coś się nie udało"
      render :new
    end
  end

  def edit
  end

  def update
    update_params = album_params.slice("title", "year", "agreed_to_publish")
    @album.update!(update_params)

    update_tags
    update_places
    add_images

    redirect_to @album
  end

  def add_photos_form
  end

  def add_photos
    add_images
    photo_service.album_photos(@album, album_params["author"])

    redirect_to @album
  end

  private

  def find_album
    @album = Album.friendly.find(params[:id])
  end

  def photo_service
    @photo_service ||= PhotoService.new
  end

  def album_params
    params.require(:album).permit(:title, :year, :agreed_to_publish, :author, :tags, :places, images:[])
  end

  def update_tags
    unless tags.blank?
      @album.tags.delete_all
      tags.split(/[,\s]+/).each do |tag_name|
        tag = Tag.find_or_create_by(name: tag_name)
        @album.tags << tag
      end
    end
  end

  def update_places
    unless places.blank?
      @album.places.delete_all
      places.split(/[,]+/).each do |place_name|
        place = Place.find_or_create_by(name: place_name)
        @album.places << place
      end
    end
  end

  def add_images
    if images
      tokens = images.map do |image|
        resized_image = MiniMagick::Image.new(image.tempfile.path).resize '1200x1200'
        photo_service.upload_token(resized_image.to_blob)
      end
      photo_service.add_media_items(tokens, @album.external_id)
      Rails.cache.delete("photos/album_#{@album.external_id}")
    end
  end

  def images
    album_params["images"]
  end

  def places
    album_params["places"]
  end

  def tags
    album_params["tags"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!


  protected

  def authenticate_admin_user!
    raise 'no entry' unless current_user.admin?
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :find_photo, only: [:edit, :update]

  def update
    @photo.update!(photo_params)
  end

  private

  def find_album
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:author)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def admin_new
    self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    yield resource if block_given?
    respond_with(resource, serialize_options(resource))
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/token_helper.rb
module TokenHelper

  def access_token
    @access_token ||= crypt.decrypt_and_verify(user.encrypted_token)
  end

  private

  def crypt
    @crypt ||= ActiveSupport::MessageEncryptor.new(Rails.application.credentials.secret_key_base[0..31])
  end

  def refresh_access_token
    response = RestClient.post "https://oauth2.googleapis.com/token", refresh_token_params
    @access_token = JSON.parse(response.body)["access_token"]
    @user.update!(encrypted_token: @crypt.encrypt_and_sign(@access_token))
  end

  def refresh_token_params
    {
      client_id: Rails.application.credentials.google[:access][:client_id],
      client_secret: Rails.application.credentials.google[:access][:client_secret],
      refresh_token: refresh_token,
      grant_type: "refresh_token"
    }
  end

  def refresh_token
    @crypt.decrypt_and_verify(user.encrypted_refresh_token)
  end

  def user
    @user ||= User.first
  end
end

app/views/albums/_form.html.erb
<%= form_with model: album do |form| %>
  <div class="grid-container">
    <div class="grid-x grid-padding-x">
      <div class="small-12 medium-5 cell">
        <%= form.text_field :title, value: album.title, placeholder: "Nazwa albumu", required: true %>
      </div>
      <div class="small-12 medium-5 cell">
        <%= form.number_field :year, value: album.year || Time.now.year, placeholder: "Rok" %>
      </div>
      <div class="small-12 medium-5 cell">
        <%= form.text_field :author, value: album.author, placeholder: "Autor zdjęć", required: true %>
      </div>
      <div class="small-12 medium-5 cell">
        <%= form.text_field :tags, value: album.tags.pluck(:name).join(', '), placeholder: "Tagi" %>
      </div>
      <div class="small-12 medium-5 cell">
        <%= form.text_field :places, value: album.places.pluck(:name).join(', '), placeholder: "Rzeka/Miejsce", required: true %>
      </div>
      <div class="small-12 cell">
        <%= form.check_box :agreed_to_publish, required: true %>
        <%= form.label :agreed_to_publish, "Zgoda autora na publikację zdjęć (WYMAGANA!)" %>
      </div>
      <% unless album.photos.any? %>
        <div class="small-12 medium-10 cell">
          <label class='button'>
            Dodaj maksymalnie 50 zdjęć
            <span style="display:none;"><%= form.file_field :images, multiple: true, accept: 'image/png,image/gif,image/jpeg,image/jpg', required: true, onchange: "updateImagesList(this)" %></span>
          </label>
        </div>
        <div class="small-12 medium-10 cell" id='image_list'>
        </div>
        <br/>
      <% end %>
      </br>
      <div class="small-12 medium-10 cell">
        <%= form.submit "Zapisz", class: :button %>
      </div>
    </div>
  </div>
<% end %>

app/views/albums/add_photos_form.html.erb
<%= form_with model: @album, url: :add_photos_album, method: :put, remote: false, class: "search-form" do |form| %>
  <div class="grid-container">
    <div class="grid-x grid-padding-x">
      <div class="small-12 medium-5 cell">
        <%= form.text_field :author, value: nil, placeholder: "Autor zdjęć", required: true %>
      </div>
      <div class="small-12 medium-5 cell">
        <label class='button'>
          Dodaj maksymalnie 50 zdjęć
          <span style="display:none;"><%= form.file_field :images, multiple: true, accept: 'image/png,image/gif,image/jpeg,image/jpg', required: true, onchange: "updateImagesList(this)" %></span>
        </label>
      </div>
      <div class="small-12 medium-5 cell" id='image_list'></div>
      </br>
      <div class="small-12 medium-5 cell">
        <%= form.submit "Zapisz", class: :button %>
      </div>
    </div>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Edytuj</h1>

<%= render partial: "form", locals: {album: @album, tags: @tags, places: @places} %>

app/views/albums/index.html.erb
<div class="row">
  <h1>Albumy   <span class="smaller-font"><%= link_to "+ dodaj nowy", new_album_path %></span></h1>
</div>

<div class="row">
  <%= search_form_for @q do |f| %>

    <div class="small-12 medium-6 large-2 columns">
      <%= f.label :title_cont, 'Tytuł Albumu' %>
      <%= f.search_field :title_cont %>
    </div>

    <div class="small-12 medium-6 large-2 columns">
      <%= f.label :year_eq, 'Rok' %>
      <%= f.search_field :year_eq %>
    </div>

    <div class="small-12 medium-6 large-2 columns">
      <%= f.label :places_id_eq, 'Rzeka/Miejsce' %>
      <%= f.collection_select :places_id_eq, Place.all, :id, :name, include_blank: true %>
    </div>

    <div class="small-12 medium-6 large-2 columns">
      <%= f.label :tags_id_eq, 'Tag' %>
      <%= f.collection_select :tags_id_eq, Place.all, :id, :name, include_blank: true %>
    </div>

    <div class="small-12 medium-6 large-2 columns">
      <%= f.label :author_cont, 'Autor' %>
      <%= f.search_field :author_cont %>
    </div>

    <div class="small-12 columns">
      <%= f.submit 'Filtruj', class: "button large"%>
    </div>
  <% end %>
</div>
  
<div class="row">
  <% @albums.each do |album| %>
    <div class="small-12 medium-6 large-3 columns">
      <div class="album-cover-photo">
        <%= link_to image_tag(album.cover_photo_url), album_path(album.external_id) %>
      </div>
      <h5><%= album.title %></h5>
      <div class="row">
        <div class="small-6 columns">Rok:</div>
      	<div class="small-6 columns"><%= album.year %></div>
        <div class="small-6 columns">Miejsce:</div>
      	<div class="small-6 columns"><%= album.place_names %></div>
        <div class="small-6 columns">Autorzy/rki:</div>
      	<div class="small-6 columns"><%= album.authors %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/albums/new.html.erb
<h1>Dodaj nowy album    <span class="smaller-font"><%= link_to "lub anuluj i wróć do listy", albums_path %></span></h1>

<%= render partial: "form", locals: {album: @album} %>

app/views/albums/show.html.erb
<% if current_user.admin? %>
  <h3 class="back-link"><%=link_to "Wróć do listy", albums_path %></h3>
<% end %>
<h1><%= @album.title %></h1>

<div class="album-data-container">
  <%=link_to "Edytuj dane", edit_album_path(@album), class: "float-right" %>
  <%=link_to "Dodaj zdjęcia", add_photos_form_album_path(@album), class: "float-right" %>
  <table class="album-data">
  	<tr>
  	  <td>rok:</td>
  	  <td><%= @album.year %></td>
  	</tr>
  	  <td>gdzie:</td>
      <td><%= @album.places.map(&:name).join(', ') %></td>
    </tr>
    <tr>
      <td>tagi:</td>
      <td><%= @album.tags.map(&:name).join(', ') %></td>
    </tr>
    <tr>
      <td>autorzy:</td>
      <td><%= @album.authors %></td>
    </tr>
  </table>
</div>

<div class="row">
  <% @photos.each do |photo| %>
    <div class="small-12 medium-6 large-3 columns">
      <div class="album-cover-photo">
        <%= link_to image_tag(photo.url), photo.url, target: :_blank %>
      </div>
      <div>
        Autor: <%= photo.author %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Habafoto" %></title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div>
      <ul class="menu align-right">
        <% if user_signed_in? %>
          <li><%= link_to "Wyloguj się, papa!", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<% if current_user.admin? %>
  <h3 class="back-link"><%=link_to "Zobacz wszystkie albumy", albums_path %></h3>
<% end %>
<div class="grid-x grid-padding-x add-text-container align-center align-bottom">
	<p class="no-margin">dodaj album</p>
</div>

<div class="grid-x grid-padding-x add-text-container align-center-middle">
	<div class="container">
  <div class="chevron"></div>
  <div class="chevron"></div>
  <div class="chevron"></div>
</div>
</div>

<div class="grid-x grid-padding-x add-button-container align-center align-top">
  <div class="row">
    <%= link_to "+", new_album_path, class: "button large add-button" %>
  </div>
</div>